threads: 16

# has to contain at least two columns: 'Accession' and 'seqs' for protein/transcript name and corresponding sequence
Seqinput: 'data/formatted_sequences.csv'
# file that is used to train the BPE algorithm
BPEinput: 'data/SwissProt_canonical.fasta'

# BPE vocabulary size
BPEvocab: 5000
# fraction of skip-grams to keep for model training, depends on sequence length and data set size
keep: 0.5
# fraction of negative word pairs (1 - 50 %, 0.5 - 33 %, ...)
negSkipgrams: 0.8
# window size where token is considered as context word (context window is target +- window size)
windowSize: 10

# dimensionality of embedding vector
embedding: 100
# model training parameters
epochs: 100
valSplit: 0.2
batchSize: 32
