
shell.executable("/bin/bash")


import pandas as pd
import os, multiprocessing
import yaml
from snakemake import utils
from snakemake.utils import min_version
from snakemake import logging

min_version("5.0")
shell.prefix("set -euo pipefail;")

features = yaml.load(open("features.yaml", "r+"), Loader=yaml.FullLoader)

snakefiles = "src/"
include: snakefiles + "model.py"

rule all:
    input:
        w5 = expand('/scratch2/hroetsc/Seq2Vec/results/weights_{sample}.csv',
                                sample = features["params"]["w5"])
        #w1 = expand('/scratch2/hroetsc/Seq2Vec/results/weights_{sample}.csv',
        #                        sample = features["params"]["w1"]),
        #w3 = expand('/scratch2/hroetsc/Seq2Vec/results/weights_{sample}.csv',
        #                        sample = features["params"]["w3"]),
        #w10 = expand('/scratch2/hroetsc/Seq2Vec/results/weights_{sample}.csv',
        #                        sample = features["params"]["w10"]),
        #w15 = expand('/scratch2/hroetsc/Seq2Vec/results/weights_{sample}.csv',
        #                        sample = features["params"]["w15"])
