shell.executable("/bin/bash")

singularity: "docker://continuumio/miniconda3:4.5.4"
import pandas as pd
import os, multiprocessing
import yaml
from snakemake.utils import min_version

min_version("5.0")
shell.prefix("set -euo pipefail;")

#config = yaml.load(open("config.yml", "r"), Loader=yaml.FullLoader)

snakefiles = "src/"
include: snakefiles + "hyperparams.py"

rule all:
    input:
        gp = 'results/hyperopt_gp.csv',
        gbrt = 'results/hyperopt_gbrt.csv',
        gp_conv = 'results/conv_gp.png',
        gbrt_conv = 'results/conv_gbrt.png',
        gp_obj = 'results/obj_gp.png',
        gbrt_obj = 'results/obj_gbrt.png'
