
shell.executable("/bin/bash")


import pandas as pd
import os, multiprocessing
import yaml
from snakemake import utils
from snakemake.utils import min_version
from snakemake import logging

min_version("5.0")
shell.prefix("set -euo pipefail;")

features = yaml.load(open("features.yaml", "r+"), Loader=yaml.FullLoader)

snakefiles = "src/"
include: snakefiles + "model.py"

rule all:
    input:
        metrics = '/scratch2/hroetsc/Seq2Vec/results/hp-subs_v5k_model_metrics_w5_d128.txt'
