shell.executable("/bin/bash")

singularity: "docker://continuumio/miniconda3:4.5.4"

import pandas as pd
import os, multiprocessing
import yaml
from snakemake import utils
from snakemake.utils import min_version
from snakemake import logging

min_version("5.0")
shell.prefix("set -euo pipefail;")

features = yaml.load(open("features.yaml", "r+"), Loader=yaml.FullLoader)

snakefiles = "src/"
include: snakefiles + "tokens.py"
include: snakefiles + "seq2vec.py"

rule all:
    input:
        model = features["embedded_sequence"]["model"],
        plot = "model.plot.done",
        sequence_repres_seq2vec = features["embedded_sequence"]["sequence_repres_seq2vec"],
        sequence_repres_seq2vec_CCR = features["embedded_sequence"]["sequence_repres_seq2vec_CCR"]
