shell.executable("/bin/bash")


import pandas as pd
import os, multiprocessing
import yaml
from snakemake import utils
from snakemake.utils import min_version
from snakemake import logging

min_version("5.0")
shell.prefix("set -euo pipefail;")

features = yaml.load(open("features.yaml", "r+"), Loader=yaml.FullLoader)

snakefiles = "src/"
include: snakefiles + "model.py"

rule all:
    input:
        skip_grams = expand('/scratch2/hroetsc/Seq2Vec/results/skipgrams_{sample}.txt',
                                sample = features["params"]),
        ids = expand('/scratch2/hroetsc/Seq2Vec/results/ids_{sample}.csv',
                                sample = features["params"])
